import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Baowen Liu
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";
        // Print the opening structure
        out.println("<html>");
        out.println("<head>");
        String title = "Empty title"; // Initialize it doesn't have title first
        // Use getChildElement method to find title index
        int titleIndex = getChildElement(channel, "title");
        // Get the content in <title>
        if (channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }
        out.println("<title>" + title + "</title>"); // Print title
        out.println("</head>");
        out.println("<body>");
        // Use getChildElement method to find link index
        int linkIndex = getChildElement(channel, "link");
        String link = channel.child(linkIndex).child(0).label();
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        // Initialize it doesn't have description first
        String description = "No description";
        // Find <description> index
        int descIndex = getChildElement(channel, "description");
        if (channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }
        // Start the table for RSS items
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";
        // Closing tags
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int index = -1; // Initialize no tag find
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            // Check XML's child is tag and find tag
            if (xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                index = i; // If find the tag, then update index
            }
        }
        return index; // Return index
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.print("<tr>");
        // Extract publication date
        String date = "No date available";
        int dateIndex = getChildElement(item, "pubDate");
        if (dateIndex != -1) {
            date = item.child(dateIndex).child(0).label();
        }
        out.print("<td>" + date + "</td>");
        // Extract source information
        String source = "No source available";
        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex != -1 && item.child(sourceIndex).numberOfChildren() > 0) {
            String sourceURL = item.child(sourceIndex).attributeValue("url");
            source = "<a href=\"" + sourceURL + "\">"
                    + item.child(sourceIndex).child(0).label() + "</a>";
        }
        out.print("<td>" + source + "</td>");
        // Extract news title or description
        String news = "No title available";
        int titleIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        // Check if the item has title (or description)
        if (titleIndex != -1 && item.child(titleIndex).numberOfChildren() > 0) {
            news = item.child(titleIndex).child(0).label(); // Update news
        } else if (descIndex != -1 && item.child(descIndex).numberOfChildren() > 0) {
            news = item.child(descIndex).child(0).label(); // Update news
        }
        String link = "";
        int linkIndex = getChildElement(item, "link"); // Find link index
        if (linkIndex != -1) {
            link = item.child(linkIndex).child(0).label();
        }
        if (!link.isEmpty()) {
            news = "<a href=\"" + link + "\">" + news + "</a>";
        }
        out.print("<td>" + news + "</td>"); // Print news
        out.println("</tr>"); // End of this row
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree rss = new XMLTree1(url); // Create a XMLTree to read feed
        // Check the RSS version(version should be 2.0)
        if (!rss.label().equals("rss") || !rss.hasAttribute("version")
                || !rss.attributeValue("version").equals("2.0")) {
            out.println("Error: Not a valid RSS feed.");
        } else { // If satisfied, then execute
            XMLTree channel = rss.child(0); // Get the <channel> element
            // Write the code to a new file
            SimpleWriter diffFile = new SimpleWriter1L(file);
            // Use outputHeader method to create an opening structure
            // Write to the new file
            outputHeader(channel, diffFile);
            // Iterate though the children of <channel> to process all item
            // To extract data, source, news
            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).isTag() && channel.child(i).label().equals("item")) {
                    XMLTree item = channel.child(i); // Create a new item XMLTree
                    processItem(item, diffFile);
                }
            }
            // Closing HTML tags to complete the file structure
            outputFooter(diffFile);
            // Close the out stream
            diffFile.close();
        }
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();
        // import simple reader and simple writer
        out.println("Enter RSS 2.0 URL: "); // Prompts user to input a RSS URL
        String url = in.nextLine(); // Read the URL
        XMLTree urlXml = new XMLTree1(url); // Create a XMLTree for input URL
        out.println("Enter output HTML file: "); // Prompts user to input a HTML file name
        String fileName = in.nextLine(); // Read the file name
        // Create output stream to write HTML file
        SimpleWriter fileOut = new SimpleWriter1L(fileName);
        // Print the structure of the first page of HTML
        fileOut.println("<html>");
        String title = urlXml.attributeValue("title");
        fileOut.println("<head>");
        fileOut.println("<title>" + title + "</title>"); // Set the title of web
        fileOut.println("</head>");
        fileOut.println("<body>");
        fileOut.println("<h1>" + title + "</h1>"); // Write the first page HTML title
        fileOut.println("<ul>"); // Start unordered list
        // Read all of the feed in the RSS feeds
        for (int i = 0; i < urlXml.numberOfChildren(); i++) {
            // Read the URL in feed
            String feedURL = urlXml.child(i).attributeValue("url");
            // Read and write a new separate HTML in this file
            String feedFile = urlXml.child(i).attributeValue("file");
            // Read the feed name for the first HTML page's name
            String feedName = urlXml.child(i).attributeValue("name");
            // Use precessFeed method to connect the first page to
            // the other separate HTML page
            processFeed(feedURL, feedFile, out);
            // Click href(feedName) then can go to the new HTML file
            fileOut.println("<li><a href=\"" + feedFile + "\">" + feedName + "</a></li>");
        }
        fileOut.println("</ul>"); // Close unordered list
        fileOut.println("</body>"); // Close body
        fileOut.println("</html>"); // Close first page HTML
        // Close all input, output streams
        in.close();
        out.close();
        fileOut.close();
    }

}
