import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Baowen Liu
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";
        // Print the opening structure
        out.println("<html>");
        out.println("<head>");
        String title = "Empty title"; // Initialize it doesn't have title first
        // Use getChildElement method to find title index
        int titleIndex = getChildElement(channel, "title");
        // Get the content in <title>
        if (channel.child(titleIndex).isTag()
                && channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }
        out.println("<title>" + title + "</title>"); // Print title
        out.println("</head>");
        out.println("<body>");
        // Use getChildElement method to find link index
        int linkIndex = getChildElement(channel, "link");
        String link = channel.child(linkIndex).child(0).label();
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        // Initialize it doesn't have description first
        String description = "No description";
        // Find <description> index
        int descIndex = getChildElement(channel, "description");
        if (channel.child(descIndex).isTag()
                && channel.child(descIndex).numberOfChildren() > 0) {
            description = channel.child(descIndex).child(0).label();
        }
        // Start the table for RSS items
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";
        // Closing tags
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int index = -1;
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).isTag() && xml.child(i).label().equals(tag)) {
                index = i;
            }
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.print("<tr>");
        // Extract publication date
        String date = "No date available";
        int dateIndex = getChildElement(item, "pubDate");
        if (dateIndex != -1 && item.child(dateIndex).isTag()
                && item.child(dateIndex).numberOfChildren() > 0) {
            date = item.child(dateIndex).child(0).label();
        }
        out.print("<td>" + date + "</td>");
        // Extract source information
        String source = "No source available";
        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex != -1 && item.child(sourceIndex).isTag()) {
            if (item.child(sourceIndex).numberOfChildren() > 0
                    && item.child(sourceIndex).hasAttribute("url")) {
                String sourceURL = item.child(sourceIndex).attributeValue("url");
                source = "<a href=\"" + sourceURL + "\">"
                        + item.child(sourceIndex).child(0).label() + "</a>";
            }
        }
        out.print("<td>" + source + "</td>");
        // Extract news title or description
        String news = "No title available";
        int titleIndex = getChildElement(item, "title");
        int descIndex = getChildElement(item, "description");
        String link = "";
        int linkIndex = getChildElement(item, "link");
        if (linkIndex != -1 && item.child(linkIndex).isTag()
                && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
        }
        if (titleIndex != -1 && item.child(titleIndex).isTag()
                && item.child(titleIndex).numberOfChildren() > 0) {
            news = item.child(titleIndex).child(0).label();
        } else if (descIndex != -1 && item.child(descIndex).isTag()
                && item.child(descIndex).numberOfChildren() > 0) {
            news = item.child(descIndex).child(0).label();
        }
        if (!link.isEmpty()) {
            news = "<a href=\"" + link + "\">" + news + "</a>";
        }
        out.print("<td>" + news + "</td>");
        out.println("</tr>");
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();
        // import simple reader and simple writer
        out.println("Enter RSS 2.0 URL: "); // Prompts user to input a RSS URL
        String url = in.nextLine(); // Read the URL
        out.println("Enter output HTML file: "); // Prompts user to input a HTML file name
        String fileName = in.nextLine(); // Read the file name
        // Create output stream to write HTML file
        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        XMLTree rss = new XMLTree1(url); // Create a XMLTree to read RSS
        // Check the RSS version(version should be 2.0)
        if (rss.label().equals("rss") && rss.hasAttribute("version")) {
            if (!rss.attributeValue("version").equals("2.0")) {
                out.println("Error: Not a valid RSS feed.");
            }
        }
        XMLTree channel = rss.child(0); // Get the <channel> element
        outputHeader(channel, fileOut); // Generate the opening HTML structure

        // Iterate though the children of <channel> to process all item
        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), fileOut);
            }
        }
        // Closing HTML tags to complete the file structure
        outputFooter(fileOut);
        // Close all input, output streams
        in.close();
        out.close();
        fileOut.close();
    }

}
